[package]
name = "minipdf"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
rust-version.workspace = true
description = "Experimental Rust implementation of MiniPdf Office-to-PDF conversion."
readme = "../../README.md"
keywords = ["pdf", "xlsx", "docx", "pptx", "converter"]
categories = ["encoding", "parser-implementations"]
exclude = ["target/"]

[dependencies]
chrono.workspace = true
flate2.workspace = true
image.workspace = true
roxmltree.workspace = true
rustybuzz.workspace = true
subsetter.workspace = true
ttf-parser.workspace = true
thiserror.workspace = true
unicode-bidi.workspace = true
zip.workspace = true