[workspace]
members = [
    "crates/minipdf",
    "crates/minipdf-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/mini-software/MiniPdf"
homepage = "https://github.com/mini-software/MiniPdf"
documentation = "https://docs.rs/minipdf"
rust-version = "1.82"

[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
roxmltree = "0.20"
rustybuzz = "0.20"
subsetter = "=0.2.3"
ttf-parser = "0.25"
thiserror = "2"
unicode-bidi = "0.3"
zip = { version = "2.2", default-features = false, features = ["deflate"] }