[package]
name = "minipdf-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "Experimental Rust CLI for MiniPdf Office-to-PDF conversion."
readme = "../../README.md"
keywords = ["pdf", "xlsx", "docx", "pptx", "cli"]
categories = ["command-line-utilities"]
exclude = ["target/"]

[[bin]]
name = "minipdf"
path = "src/main.rs"

[dependencies]
clap.workspace = true
minipdf = { version = "0.6.0", path = "../minipdf" }
ttf-parser.workspace = true