/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PageSize {
  width: number
  height: number
}
export interface ConversionOptions {
  pageSize?: PageSize
}
export interface RegisteredFont {
  name: string
  data: Buffer
}
export declare function convertToPdf(inputPath: string, outputPath: string, options?: ConversionOptions | undefined | null): void
export declare function convertToPdfBytes(inputPath: string, options?: ConversionOptions | undefined | null): Buffer
export declare function convertBytesToPdf(input: Buffer, options?: ConversionOptions | undefined | null): Buffer
export declare function detectOfficeFormat(input: Buffer): string
export declare function registerFont(name: string, fontData: Buffer): void
export declare function registeredFonts(): Array<RegisteredFont>
