/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  const { glibcVersionRuntime } = process.report.getReport().header
  return !glibcVersionRuntime
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'minipdf-node.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.android-arm64.node')
          } else {
            nativeBinding = require('minipdf-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'minipdf-node.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.android-arm-eabi.node')
          } else {
            nativeBinding = require('minipdf-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'minipdf-node.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.win32-x64-msvc.node')
          } else {
            nativeBinding = require('minipdf-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'minipdf-node.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('minipdf-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'minipdf-node.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('minipdf-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'minipdf-node.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./minipdf-node.darwin-universal.node')
      } else {
        nativeBinding = require('minipdf-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'minipdf-node.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.darwin-x64.node')
          } else {
            nativeBinding = require('minipdf-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'minipdf-node.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.darwin-arm64.node')
          } else {
            nativeBinding = require('minipdf-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'minipdf-node.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./minipdf-node.freebsd-x64.node')
      } else {
        nativeBinding = require('minipdf-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-x64-musl.node')
            } else {
              nativeBinding = require('minipdf-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-x64-gnu.node')
            } else {
              nativeBinding = require('minipdf-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-arm64-musl.node')
            } else {
              nativeBinding = require('minipdf-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('minipdf-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('minipdf-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('minipdf-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('minipdf-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'minipdf-node.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./minipdf-node.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('minipdf-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'minipdf-node.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./minipdf-node.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('minipdf-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  const detail = loadError ? `: ${loadError.message}` : ''
  throw new Error(
    `Failed to load MiniPdf native binding for ${platform}/${arch}${detail}. ` +
      'Reinstall minipdf with optional dependencies enabled or build it from source.',
    { cause: loadError || undefined }
  )
}

const { convertToPdf, convertToPdfBytes, convertBytesToPdf, detectOfficeFormat, registerFont, registeredFonts } = nativeBinding

module.exports.convertToPdf = convertToPdf
module.exports.convertToPdfBytes = convertToPdfBytes
module.exports.convertBytesToPdf = convertBytesToPdf
module.exports.detectOfficeFormat = detectOfficeFormat
module.exports.registerFont = registerFont
module.exports.registeredFonts = registeredFonts
