<#
.SYNOPSIS
    Create a new version release (auto-triggers NuGet publish + AOT cross-platform build)

.DESCRIPTION
    1. Create git tag v<Version>
    2. Push tag to remote
    3. Create GitHub Release (triggers nuget-publish + release-aot workflows)

.PARAMETER Version
    Version number, e.g. 0.23.0 (without the v prefix)

.PARAMETER Notes
    Release notes text (optional, auto-generated by default)

.PARAMETER Draft
    Create as a draft release (won't trigger workflows, must be published manually)

.PARAMETER Prerelease
    Mark as a prerelease version

.EXAMPLE
    scripts/New-Release.ps1 -Version 0.23.0
    scripts/New-Release.ps1 -Version 0.24.0-preview1 -Prerelease
    scripts/New-Release.ps1 -Version 0.23.0 -Notes "Fix border rendering"
#>
param(
    [Parameter(Mandatory)]
    [string]$Version,

    [string]$Notes,

    [switch]$Draft,

    [switch]$Prerelease
)

$ErrorActionPreference = 'Stop'

# Validate version format
if ($Version -notmatch '^\d+\.\d+\.\d+(-[\w.]+)?$') {
    Write-Error "Invalid version format: '$Version'. Expected: Major.Minor.Patch (e.g., 0.23.0 or 0.23.0-preview1)"
    return
}

$tag = "v$Version"

# Check gh CLI
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "GitHub CLI (gh) is required. Install: https://cli.github.com/"
    return
}

# Check clean working tree
$status = git status --porcelain
if ($status) {
    Write-Warning "Working tree has uncommitted changes:"
    git status --short
    $confirm = Read-Host "Continue anyway? (y/N)"
    if ($confirm -ne 'y') { return }
}

# Check tag doesn't already exist
$existingTag = git tag -l $tag
if ($existingTag) {
    Write-Error "Tag '$tag' already exists. Delete it first with: git tag -d $tag; git push origin :refs/tags/$tag"
    return
}

# Create and push tag
Write-Host "Creating tag $tag ..." -ForegroundColor Cyan
git tag $tag
if ($LASTEXITCODE -ne 0) { Write-Error "Failed to create tag"; return }

Write-Host "Pushing tag $tag ..." -ForegroundColor Cyan
git push origin $tag
if ($LASTEXITCODE -ne 0) {
    git tag -d $tag
    Write-Error "Failed to push tag (local tag removed)"
    return
}

# Build gh release command
$ghArgs = @('release', 'create', $tag, '--title', $tag)

if ($Notes) {
    $ghArgs += '--notes'
    $ghArgs += $Notes
} else {
    $ghArgs += '--generate-notes'
}

if ($Draft)      { $ghArgs += '--draft' }
if ($Prerelease) { $ghArgs += '--prerelease' }

Write-Host "Creating GitHub Release $tag ..." -ForegroundColor Cyan
& gh @ghArgs
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to create release. Tag '$tag' was pushed — delete manually if needed."
    return
}

Write-Host ""
Write-Host "Release $tag created successfully!" -ForegroundColor Green
Write-Host "Triggered workflows:" -ForegroundColor Yellow
Write-Host "  - NuGet Publish (MiniPdf + MiniPdf.Cli)" -ForegroundColor Yellow
Write-Host "  - AOT Binaries (6 platforms)" -ForegroundColor Yellow
Write-Host ""
Write-Host "Monitor: gh run list --workflow=nuget-publish.yml ; gh run list --workflow=release-aot.yml" -ForegroundColor DarkGray
